"""documents_vault_revamp

Revision ID: 981c3a0bcb59
Revises: c4e8a91b2f70
Create Date: 2026-09-12 12:31:59.696295

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "981c3a0bcb59"
down_revision: Union[str, Sequence[str], None] = "c4e8a91b2f70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Alembic does not autogenerate Postgres enum value adds.
    # Names match SQLAlchemy Enum member names (see create_documents_table).
    op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'POLLUTION'")
    op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'OTHER'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("custom_label", sa.String(), nullable=True))
    op.add_column("documents", sa.Column("identifier", sa.String(), nullable=True))
    op.drop_column("documents", "original_filename")
    # ### end Alembic commands ###

    # RC never expires — clear leftover dates from the old vault UI.
    op.execute(
        "UPDATE documents SET expiry_date = NULL "
        "WHERE document_type = 'REGISTRATION_CERTIFICATE'"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column(
            "original_filename",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            server_default="document",
        ),
    )
    op.alter_column("documents", "original_filename", server_default=None)
    op.drop_column("documents", "identifier")
    op.drop_column("documents", "custom_label")
    # ### end Alembic commands ###
    # Postgres cannot easily remove enum values; leave POLLUTION/OTHER in place.
